---
- hosts: all
  become: false
  tasks:
    - name: pull repository
      shell: git pull origin master
      args:
        chdir: /home/bisnis/public
      register: command_output
    - debug: 
            var=command_output.stdout_lines