---
- hosts: all
  become: false
  tasks:
    - name: pull repository
      shell: 
         "ls -l"
      args:
        chdir: "/home/bisnis/public" 
      register: fileout
      
    - debug: 
            var: fileout.stdout_lines