---
- hosts: all
  become: false
  tasks:
    - name: pull repository
      shell: 
         "./deploy.sh"
      args:
        chdir: "/home/bisnis/public" 
      register: fileout
      
    - debug: msg="{{ fileout.stdout-lines }}"